server:
  port: 8765

spring:
  application:
    name: rest
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  cache:
    ehcache:
      config: classpath:/ehcache.xml
  data:
    mongodb:
      uri: mongodb://root:123456@localhost:27017
      database: test
      authentication-database: test

j2cache:
  config-location: classpath:/j2cache.properties
  cache-clean-mode: active
  open-spring-cache: true
