server:
  port: 8765

spring:
  application:
    name: rest
  cache:
    ehcache:
      config: classpath:/ehcache.xml
  data:
    mongodb:
      host: 192.168.44.101
      port: 27017
      username: devroot
      password: ylzWXSB2019
      database: wxsb_dev
    solr:
      host: http://localhost:8080/solr

j2cache:
  config-location: classpath:/j2cache.properties
  cache-clean-mode: active
  open-spring-cache: true

project:
  jwt:
    secret: ac388ikUI
    expired: 3
    patternPath: false
    patternAnno: true
