server:
  port: 8778

spring:
  application:
    name: website
  cache:
    ehcache:
      config: classpath:/ehcache.xml

j2cache:
  config-location: classpath:/j2cache.properties
  cache-clean-mode: active
  open-spring-cache: true